### ISSUE TITLE
pad_token

### ISSUE THREAD

**Issue by WayneMind** [LegallyCoder/mamba-hf#2]
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

**Comment by LegallyCoder** [comment]
You can try these:
tokenizer.pad_token = tokenizer.eos_token
tokenizer.add_special_tokens({'pad_token': '[PAD]'})

And this issue isn't my problem i guess gptneox's tokenizer doesn't have PAD token.
